create extension if not exists vector;

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'New conversation',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  module_code text,
  source_type text not null default 'student_upload' check (source_type in ('student_upload','nwu_official','academic')),
  source_url text,
  created_at timestamptz not null default now()
);

alter table public.documents
  add column if not exists conversation_id uuid references public.conversations(id) on delete cascade;

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  embedding_cloudflare vector(384),
  created_at timestamptz not null default now()
);

-- Existing OpenAI embeddings, if present, are preserved; Cloudflare vectors use a separate column.
alter table public.document_chunks
  add column if not exists embedding_cloudflare vector(384);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;

drop policy if exists "users manage own conversations" on public.conversations;
create policy "users manage own conversations" on public.conversations for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own messages" on public.messages;
create policy "users manage own messages" on public.messages for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users manage own documents" on public.documents;
create policy "users manage own documents" on public.documents for all
  using (auth.uid() = user_id or source_type = 'nwu_official')
  with check (auth.uid() = user_id);

drop policy if exists "users read own chunks" on public.document_chunks;
create policy "users read own chunks" on public.document_chunks for select
  using (
    auth.uid() = user_id
    or exists (
      select 1 from public.documents d
      where d.id = document_chunks.document_id and d.source_type = 'nwu_official'
    )
  );

grant select, insert, update on public.conversations to authenticated;
grant select, insert on public.messages to authenticated;
grant select on public.documents, public.document_chunks to authenticated;
grant all privileges on public.conversations, public.messages, public.documents, public.document_chunks to service_role;

create index if not exists conversations_user_updated_idx
  on public.conversations (user_id, updated_at desc);
create index if not exists messages_conversation_created_idx
  on public.messages (conversation_id, created_at);
create index if not exists document_chunks_user_idx
  on public.document_chunks (user_id);
create index if not exists document_chunks_embedding_cloudflare_idx
  on public.document_chunks using ivfflat (embedding_cloudflare vector_cosine_ops) with (lists = 100);

create index if not exists documents_conversation_idx
  on public.documents (user_id, conversation_id, created_at)
  where source_type = 'student_upload';

drop function if exists public.match_document_chunks_cloudflare(vector, integer, uuid);
drop function if exists public.match_document_chunks_cloudflare(vector, integer);
create or replace function public.match_document_chunks_cloudflare(
  query_embedding vector(384),
  match_count integer default 8,
  target_conversation_id uuid default null
)
returns table (
  id bigint,
  document_id uuid,
  content text,
  similarity float,
  source_name text,
  module_code text,
  source_type text,
  source_url text
)
language sql stable as $$
  select c.id, c.document_id, c.content,
         1 - (c.embedding_cloudflare <=> query_embedding) as similarity,
         d.file_name, d.module_code, d.source_type, d.source_url
  from public.document_chunks c
  join public.documents d on d.id = c.document_id
  where (
      d.source_type = 'nwu_official'
      or (
        c.user_id = auth.uid()
        and d.user_id = auth.uid()
        and d.source_type = 'student_upload'
        and d.conversation_id = target_conversation_id
      )
    )
    and c.embedding_cloudflare is not null
  order by c.embedding_cloudflare <=> query_embedding
  limit match_count;
$$;

grant execute on function public.match_document_chunks_cloudflare(vector, integer, uuid) to authenticated, service_role;

create or replace function public.touch_conversation()
returns trigger language plpgsql as $$
begin
  update public.conversations set updated_at = now() where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists messages_touch_conversation on public.messages;
create trigger messages_touch_conversation after insert on public.messages
  for each row execute function public.touch_conversation();

insert into storage.buckets (id, name, public)
values ('tmj-documents', 'tmj-documents', false)
on conflict (id) do nothing;

drop policy if exists "users upload own tmj documents" on storage.objects;
create policy "users upload own tmj documents" on storage.objects for insert to authenticated
  with check (bucket_id = 'tmj-documents' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "users read own tmj documents" on storage.objects;
create policy "users read own tmj documents" on storage.objects for select to authenticated
  using (bucket_id = 'tmj-documents' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "users delete own tmj documents" on storage.objects;
create policy "users delete own tmj documents" on storage.objects for delete to authenticated
  using (bucket_id = 'tmj-documents' and (storage.foldername(name))[1] = auth.uid()::text);

notify pgrst, 'reload schema';
