const CONFIG={supabaseUrl:"https://kiaaamxjtvenyaujpysf.supabase.co",supabaseAnonKey:"sb_publishable_F3MdZEjCS99N9oY9z7m9PQ_lwY0FUTr"};let supabase=null;let session=null;let currentConversation=null;let authMode="signin";const $=id=>document.getElementById(id);
function ready(){if(CONFIG.supabaseUrl.startsWith("YOUR_")){console.warn("Configure Supabase before enabling accounts.");return}supabase=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey);supabase.auth.onAuthStateChange((_event,newSession)=>{session=newSession;updateAuthUI();loadConversations()});supabase.auth.getSession().then(({data})=>{session=data.session;updateAuthUI();loadConversations()})}
function updateAuthUI(){$("authButton").textContent=session?"Sign out":"Sign in";$("newChat").disabled=!session;$("uploadPanel").hidden=!session;if(session)loadConversations()}
$("authButton").addEventListener("click",async()=>{if(session){await supabase.auth.signOut();return}$("authDialog").showModal()});
$("authToggle").addEventListener("click",()=>{authMode=authMode==="signin"?"signup":"signin";$("authTitle").textContent=authMode==="signin"?"Sign in":"Create account";$("authSubmit").textContent=authMode==="signin"?"Sign in":"Create account";$("authName").hidden=authMode==="signin"});
$("authForm").addEventListener("submit",async e=>{e.preventDefault();if(!supabase){$("authStatus").textContent="Account services are not configured yet.";return}const email=$("authEmail").value.trim(),password=$("authPassword").value,name=$("authName").value.trim();const result=authMode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(result.error)$("authStatus").textContent=result.error.message;else if(result.data.session)$("authDialog").close();else $("authStatus").textContent="Check your email to confirm your account."});
$("newChat").addEventListener("click",()=>{currentConversation=null;$("messages").innerHTML='<div class="welcome"><p class="eyebrow">NEW CONVERSATION</p><h2>What are you studying?</h2></div>'});
$("chatForm").addEventListener("submit",async e=>{e.preventDefault();if(!session){$("authDialog").showModal();return}const prompt=$("prompt").value.trim();if(!prompt)return;addMessage("user",prompt);$("prompt").value="";const thinking=addMessage("assistant","Searching relevant academic material…");try{const response=await fetch("/.netlify/functions/chat",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token},body:JSON.stringify({message:prompt,conversationId:currentConversation?.id||null})});const data=await response.json();thinking.textContent=data.reply||data.error||"No response received.";if(data.conversationId)currentConversation={id:data.conversationId};loadConversations()}catch(err){thinking.textContent="The agent could not connect. Please try again."}});
$("uploadForm").addEventListener("submit",async e=>{e.preventDefault();if(!session)return;const file=$("documentFile").files[0],moduleCode=$("moduleCode").value.trim().toUpperCase();if(!file){$("uploadStatus").textContent="Choose a document first.";return}if(file.size>10*1024*1024){$("uploadStatus").textContent="Maximum file size is 10 MB.";return}if(!file.name.match(/\.(pdf|docx|txt|md)$/i)){ $("uploadStatus").textContent="Supported files: PDF, DOCX, TXT and MD.";return}$("uploadStatus").textContent="Uploading and indexing…";const path=session.user.id+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const upload=await supabase.storage.from("tmj-documents").upload(path,file,{contentType:file.type||"application/octet-stream",upsert:false});if(upload.error){$("uploadStatus").textContent=upload.error.message;return}const response=await fetch("/.netlify/functions/index-document",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token},body:JSON.stringify({storagePath:path,fileName:file.name,moduleCode})});const data=await response.json();$("uploadStatus").textContent=data.message||data.error||"Done.";if(data.ok)$("uploadForm").reset()});
function addMessage(role,text){const el=document.createElement("div");el.className="message "+role;el.textContent=text;$("messages").appendChild(el);$("messages").scrollTop=$("messages").scrollHeight;return el}
async function loadConversations(){if(!supabase||!session)return;const {data,error}=await supabase.from("conversations").select("id,title,updated_at").order("updated_at",{ascending:false}).limit(30);if(error){$("conversationList").innerHTML='<p class="muted">Could not load conversations.</p>';return}$("conversationList").innerHTML="";for(const c of data||[]){const el=document.createElement("div");el.className="conversation";el.textContent=c.title||"New conversation";el.onclick=()=>loadConversation(c.id);$("conversationList").appendChild(el)}if(!data?.length)$("conversationList").innerHTML='<p class="muted">No saved conversations yet.</p>'}
async function loadConversation(id){if(!supabase||!session)return;const {data,error}=await supabase.from("messages").select("role,content").eq("conversation_id",id).order("created_at",{ascending:true});if(error)return;currentConversation={id};$("messages").innerHTML="";(data||[]).forEach(m=>addMessage(m.role,m.content))}
ready();